### ISSUE TITLE
Need Sticky Action Bar in Drawer Header

### ISSUE THREAD

**Issue by mdjacobs** [saddlebackdev/react-cm-ui#1]
Need the ability to have an Action Bar below Nav that will be sticky as well.  Adding the action bar to the corresponding component keeps logic close without having to pass props/state through to a parent/grandparent.

![rkaktcumlg](https://user-images.githubusercontent.com/1649726/27455349-d7f48f8a-5751-11e7-8a5f-bf27b3e01f93.gif)

**Comment by morethanfire** [comment]
Commit https://github.com/saddlebackdev/react-cm-ui/commit/bb3640eb10d4137e29352ee96a911c64213557ef adds the capability to do this.
