### ISSUE TITLE
BannerItem is not exported in react-cm-ui library

### ISSUE THREAD

**Issue by gbulatov** [saddlebackdev/react-cm-ui#2]
BannerItem is used in "Select Persons to merge" page to select an action, so it does not work now

**Comment by morethanfire** [comment]
@IlyaRadinsky can you verify that version 1.0.2 fixes this issue?

**Comment by IlyaRadinsky** [comment]
@morethanfire yep, version 1.0.2 fixed this

**Comment by morethanfire** [comment]
Awesome!
