### ISSUE TITLE
Collapsible Cards - Expand/Collapse icons might be backwards?

### ISSUE THREAD

**Issue by groberts314** [saddlebackdev/react-cm-ui#20]
*Do you want to request a feature or report a bug?*
Possible bug

*What is the current behavior?*
On the collapsible cards, when the card is expanded, icon is `+`.  When collapsed, it is an `X`.  Might that be backwards?  When expanded, `X` (or maybe `-` or something) makes more sense to close/collapse, and when collapsed, `+` makes sense to expand.

*If the current behavior is a bug, please provide the steps to reproduce.*
View any page with Collapsible Cards (React CM UI documentation website or HC person record)

*Which version of react-cm-ui, and which browser / OS are affected by this issue? Did this work in previous versions of react-cm-ui?*
All versions of React CM UI up through 1.8.23.
All OSs and browsers impacted equally.
Observed on Windows 7, Google Chrome Version 64.0.3282.186 (Official Build) (64-bit)

**Comment by groberts314** [comment]
VSTS Cross Reference: [Bug 10348](https://saddlebackchurch.visualstudio.com/DefaultCollection/Church%20Management/_workitems/edit/10348)

**Comment by morethanfire** [comment]
commit #7554c7300c18ef3223710b84c57db07274efc76f fixed this issue and has been put into release 1.13.1.
