### ISSUE TITLE
JavaScript console warning from Drawer Component

### ISSUE THREAD

**Issue by groberts314** [saddlebackdev/react-cm-ui#22]
*Do you want to request a feature or report a bug?* **Bug**

*What is the current behavior?*
When the drawer is closed, sometimes get this JavaScript warning:
```
warning.js:33 Warning: setState(...): Can only update a mounted or mounting component. This usually means you called setState() on an unmounted component. This is a no-op. Please check the code for the Portal component.
printWarning @ warning.js:33
warning @ warning.js:57
getInternalInstanceReadyForUpdate @ ReactUpdateQueue.js:46
enqueueSetState @ ReactUpdateQueue.js:207
ReactComponent.setState @ ReactBaseClasses.js:62
resetPortalState @ portal.js:140
_onAnimationComplete @ Drawer.react.js:267
```

*If the current behavior is a bug, please provide the steps to reproduce.*
I was troubleshooting the Person Merge workflow from a Person record specifically.  So these are the steps I took in the consuming Healthy Church application, version 1.7.3 hotfix branch, created from version 1.7.2, which is current production (`master`), behind `dev` branch a bit:
1. Search for a person
2. Navigate to that Person's record
3. Click **Merge** button in action bar (upper right).  This opens the Person Search Drawer.
4. Search for a different person record to merge.
5. Expand it and click **Select** button.
6. Drawer closes, and we navigate over to Merge page.  This warning is logged in console.

*Which version of react-cm-ui, and which browser / OS are affected by this issue? Did this work in previous versions of react-cm-ui?*
React CM UI 1.10.3
Google Chrome Version 66.0.3359.181 (Official Build) (64-bit)
Windows 7

I don't believe this is browser and/or OS specific, and I believe it's been a problem for many previous versions of React CM UI (probably all along since we added the `Drawer` component, but I don't know for sure).

I'm not sure if this is actually an issue with the upstream dependency `Portal` component from `react-portal` package, or if this is an issue with our animation code in our `Drawer` component.

**Comment by groberts314** [comment]
@morethanfire ... does this issue sound at all familiar, and is it on your radar?  Not that it's necessarily urgent, but it'd be nice to fix it if we can.

**Comment by morethanfire** [comment]
I love this issue script!

**Comment by morethanfire** [comment]
I'll take a look at this hopefully today. I haven't seen this warning before and I'm curious if it has to do with Drawer itself or the Drawer's child component.

**Comment by morethanfire** [comment]
@groberts314, do we know if this is still an issue?

**Comment by groberts314** [comment]
Not off the top of my head; I'd have to check.  I'd have to imagine this refers to `<DrawerDeprecated>` now as well. :-)

**Comment by morethanfire** [comment]
Because of how old this Issue I figured bug may not be issue anymore. I walked through the steps this morning and I'm confirming this is no longer an issue. Closing.
