### ISSUE TITLE
Inconsistency across components with respect to "disabled" prop

### ISSUE THREAD

**Issue by groberts314** [saddlebackdev/react-cm-ui#25]
*Do you want to request a feature or report a bug?*
Bug/Inconsistency

*What is the current behavior?*
The `Dropdown` and `PhoneInput` components have a `disable` prop while other components have `disabled` props.  All components should use `disabled` for consistency.

*If the current behavior is a bug, please provide the steps to reproduce.*
N/A

*Which version of react-cm-ui, and which browser / OS are affected by this issue? Did this work in previous versions of react-cm-ui?*
All released versions up to and including 1.11.11
Not browser or OS specific; it is an issue with the component prop definitions.

**Comment by groberts314** [comment]
Cross reference in VSTS: [Backlog Item 10347](https://saddlebackchurch.visualstudio.com/DefaultCollection/Church%20Management/_workitems/edit/10347)

**Comment by morethanfire** [comment]
I am going to open a PR with the work that adds the remaining components that need to deprecated `disabled` and add the `disable` prop.
