### ISSUE TITLE
Feature Request: Dual List Box Component

### ISSUE THREAD

**Issue by groberts314** [saddlebackdev/react-cm-ui#4]
*Do you want to request a feature or report a bug?* **Feature / New Component**
*What is the current behavior?* **Desired component does not exist.**
*If the current behavior is a bug, please provide the steps to reproduce.* **N/A**
*Which version of react-cm-ui, and which browser / OS are affected by this issue? Did this work in previous versions of react-cm-ui?*
**React CM UI 1.0.2 / all browsers and OSes**

Would like a "dual list box" component.  Here are a couple of examples, but neither looks suitable.
1. https://www.npmjs.com/package/react-dual-listbox / https://github.com/jakezatecky/react-dual-listbox (depends on React 15 :-( )
2. https://www.npmjs.com/package/react-listbox / https://github.com/Sridatta19/react-listbox (depends on something called "Ramda" which seems to have a _huge_ dependency graph)

Possibly we can steal sources from (1) and get it to work with React 0.14 ...?

**Comment by groberts314** [comment]
Going to give Option 1 listed above ( `react-dual-listbox` ) a whirl and see if it will work in React 0.14.  The package author has agreed that if no major issues arise, he will relax the react version in the dependencies in his package.json; see https://github.com/jakezatecky/react-dual-listbox/issues/23

I'm not sure if we need/want to wrap this on our own component and/or provide our own styles in `react-cm-ui` or not.

I need something like this for the re-factored User Manager (for user security/access control administration) in CM, which I am tackling near the beginning of Sprint 22.  When I get there in the next few days, I'll probably start with adding that package directly to the CM client project.

**Comment by morethanfire** [comment]
As we discussed in our Google hangout yesterday, July 12th, we are going to go with our *Dropdown* multiple selection module for now and see how this goes for the future we need this for.
I'm closing this issue, but if needed, we can reopen down the road.
