### ISSUE TITLE
Feature Request: "Directory Tree" Component

### ISSUE THREAD

**Issue by groberts314** [saddlebackdev/react-cm-ui#5]
*Do you want to request a feature or report a bug?* **Feature / New Component**
*What is the current behavior?* **Desired component does not exist.**
*If the current behavior is a bug, please provide the steps to reproduce.* **N/A**
*Which version of react-cm-ui, and which browser / OS are affected by this issue? Did this work in previous versions of react-cm-ui?* **React CM UI 1.0.2 / all browsers and OSes**

I would like a directory tree/tree viewer component.  Going to use it for re-factoring Security Role Manager in CM (near the beginning of Sprint 22), to remove the restriction that all permissions must be "CRUD" verbs (Create Foo, Read Foo, Update Foo, Delete Foo).  The tree view component would be used to browse the feature/category hierarchy under which the permissions reside (instead of the present "blades"), and instead of using the circular, three-state check boxes going horizontally, the permission "leaves" of the tree will go vertically, allowing any number of "sibling" permission leaves at a given level.

I have not done an exhaustive search of existing React components that do this, but I imagine there are plenty of them out there.  I imagine if we do choose one, we'll potentially want to wrap it and/or style it, so we might want it in here.  If nothing is available in here when I need to do development, I may choose an existing 3rd party component and reference it directly from CM client project for now.

**Comment by morethanfire** [comment]
This sounds like a good idea, but we'll need to bring in @aaronsampson on discussing this feature/module. Aaron, what are you thinking?

**Comment by morethanfire** [comment]
I am going to tackle this in sprint 22.

**Comment by morethanfire** [comment]
Commit https://github.com/saddlebackdev/react-cm-ui/commit/f4dc00db1d2f950085ba530d5c30197f702a505d adds this basic feature.
