### ISSUE TITLE
TreeMenu Error

### ISSUE THREAD

**Issue by osn1978** [saddlebackdev/react-cm-ui#6]
Version 1.1.4

Hi guys,
library with version more than 1.0.0 is not worked.

ERROR in ./node_modules/react-tree-menu/src/TreeMenu.jsx
Module parse failed: C:\Work\Tateeda\Peace\Mission-Mgmt\Peace\Sbc.Peace.UI\node_modules\react-tree-menu\src\TreeMenu.jsx Unexpected token (57:6)
You may need an appropriate loader to handle this file type.
|
|     return (
|       <div className={props.classNamePrefix}>
|         {this._getTreeNodes()}
|       </div>);
 @ ./node_modules/react-tree-menu/index.js 1:10-39 3:15-44
 @ ./node_modules/react-cm-ui/lib/Modules/TreeMenu.react.js
 @ ./node_modules/react-cm-ui/lib/index.js
 @ ./src/components/activities/ActivitiesPage.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./src/index

ERROR in ./node_modules/react-tree-menu/src/TreeNode.jsx
Module parse failed: C:\Work\Tateeda\Peace\Mission-Mgmt\Peace\Sbc.Peace.UI\node_modules\react-tree-menu\src\TreeNode.jsx Unexpected token (59:15)
You may need an appropriate loader to handle this file type.
|       collapseIconClass: "",
|       labelFactory: function (labelClassName, displayLabel) {
|         return <label className={labelClassName}>{displayLabel}</label>;
|       },
|       checkboxFactory: function (className, isChecked) {
 @ ./node_modules/react-tree-menu/index.js 4:15-44
 @ ./node_modules/react-cm-ui/lib/Modules/TreeMenu.react.js
 @ ./node_modules/react-cm-ui/lib/index.js
 @ ./src/components/activities/ActivitiesPage.js
 @ ./src/routes.js
 @ ./src/index.js
 @ multi eventsource-polyfill webpack-hot-middleware/client?reload=true ./src/index

**Comment by groberts314** [comment]
You need a webpack loader that handles JSX files.  I thought @morethanfire and @raoufr were assisting with that for the PEACE MTM application.
For the Church Management application, we have the following:

```JavaScript
{
    test: /\.jsx$/,
    include: [
        path.resolve(__dirname, 'node_modules', 'react-tree-menu')
    ],
    loader: 'babel-loader',
    options: {
        presets: ['es2015', 'react'],
        plugins: [ 'add-module-exports' ]
    }
}
```

**Comment by osn1978** [comment]
It didn't help. The same error.

**Comment by groberts314** [comment]
Can you share your entire webpack config file?

**Comment by osn1978** [comment]
import webpack from 'webpack';
import path from 'path';

import ExtractTextPlugin from 'extract-text-webpack-plugin';

const GLOBALS = {
    'process.env.NODE_ENV': JSON.stringify('local'),
    'process.env.Authority': JSON.stringify('https://identity-dev.saddleback.com'),
    'process.env.OIDCRedirectUri': JSON.stringify('http://localhost:3000'),
    'process.env.OIDCLogoutRedirectUri': JSON.stringify('http://localhost:3000'),
    'process.env.OIDCSilentRedirectUri': JSON.stringify('http://localhost:3000'),
    'process.env.ApiUrl': JSON.stringify('http://localhost:58871/api/'),
    'process.env.SaddlebackApi': JSON.stringify('//branch.saddleback.com/api/')
};

export default {
    devtool: 'cheap-module-eval-source-map', //'cheap-module-eval-source-map', //'source-map'
    entry: [
        'eventsource-polyfill', // necessary for hot reloading with IE
        'webpack-hot-middleware/client?reload=true', //note that it reloads the page if hot module reloading fails.
        './src/index'
    ],
    target: 'web',
    output: {
        path: __dirname + '/dist', // Note: Physical files are only output by the production build task `npm run build`.
        publicPath: '/',
        filename: 'bundle.js'
    },
    devServer: {
        historyApiFallback: true,
        contentBase: './src',
        hot: true
    },
    plugins: [
        new webpack.HotModuleReplacementPlugin(),
        new webpack.DefinePlugin({
            'process.env.NODE_ENV': GLOBALS["process.env.NODE_ENV"],
            'process.env.Authority': GLOBALS["process.env.Authority"],
            'process.env.OIDCRedirectUri': GLOBALS["process.env.OIDCRedirectUri"],
            'process.env.OIDCLogoutRedirectUri': GLOBALS["process.env.OIDCLogoutRedirectUri"],
            'process.env.OIDCSilentRedirectUri': GLOBALS["process.env.OIDCSilentRedirectUri"],
            'process.env.ApiUrl': GLOBALS["process.env.ApiUrl"],
            'process.env.SaddlebackApi': GLOBALS["process.env.SaddlebackApi"]
        }),
        new ExtractTextPlugin({
            filename: 'styles.css',
            disable: false,
            allChunks: true
        })
    ],
    module: {
        rules: [
            {
                test: /\.js$/,
                exclude: [/node_modules/],
                loader: 'babel-loader',
                options: {
                    presets: ['es2015', 'react']
                }
            },
            {
                test: /\.jsx$/,
                include: [
                    path.resolve(__dirname, 'node_modules', 'react-tree-menu')
                ],
                loader: 'babel-loader',
                options: {
                    presets: ['es2015', 'react'],
                    plugins: ['add-module-exports']
                }
            },
            { test: /\.css$/, use: ['style-loader', 'css-loader'] },
            { test: /\.scss$/, use: ['style-loader', 'css-loader', 'sass-loader'] },
            {
                test: /.(ico|png|jpg|gif|svg|eot|ttf|woff|woff(2)?)(\?[a-z0-9=.]+)?$/,
                loader: 'file-loader?name=[path][name].[ext]?[hash]&context=./src'
            },
            {
                test: /.json$/,
                loader: 'json-loader'
            }
        ]
    },
    resolve: {
        extensions: [
            '.js',
            '.jsx',
            '.scss',
            '.ico',
            '.png',
            '.jpg',
            '.gif',
            '.eot',
            '.ttf',
            '.woff',
            '.woff2',
            '.svg',
            '.json'
        ],
        modules: [
            'node_modules',
            'src'
        ],
        alias: {
            react: path.resolve('./node_modules/react'),
            'react-dom': path.resolve('./node_modules/react-dom'),
            'css-cm-ui': path.join(__dirname, '/node_modules/react-cm-ui/lib/css/Style.css')
        }
    }
};

**Comment by groberts314** [comment]
Wondering if it is maybe not resolving the path correctly in the include property there...?
maybe try: `path.resolve('./node_modules/react-tree-menu')` ?

**Comment by groberts314** [comment]
There is now a version 1.1.5 that does not export the Tree Menu; please see if you can upgrade and use your original webpack config.

**Comment by groberts314** [comment]
Side note: I'll not that `.jsx` was not in the `resolve: { extensions: [] ... }` setting in Church Management's webpack config ... I'm wondering if that had something to do with the fact that it is all fine in CM, but not working for PEACE.  CM application does not export and load JSX files directly ... all of our JSX is embedded in component `render()` functions.

**Comment by groberts314** [comment]
Per @osn1978 

> Hi guys,
> i got latest react-cm-ui.
> Now all works perfect, thanks.

I'm going to go ahead and close this issue.  I felt the `wontfix` label was appropriate since we technically didn't fix the issue; we simply stopped exporting the offending control.  Also, I think we're going to remove that tree control completely in a future release (and go a different way for the intended usage of it, at least in the Church Management application).  So clearly we're also punting on the larger issue of supporting loading any JSX files exposed by components in this library for now.
