### ISSUE TITLE
Loader bug

### ISSUE THREAD

**Issue by osn1978** [saddlebackdev/react-cm-ui#7]
Version 1.1.5

Error in browser console:

Warning: Unknown DOM property fill-rule. Did you mean fillRule?
    in g (created by Loader)
    in svg (created by Loader)
    in div (created by Loader)
    in Loader (created by ActivitiesGridView).....

**Comment by morethanfire** [comment]
Which browser was this warning in?

**Comment by osn1978** [comment]
Chrome

**Comment by morethanfire** [comment]
Windows?

**Comment by osn1978** [comment]
I don't know why you ask, but yes.
React do not support fill-rule tag. Just replace it to fillRule.

**Comment by morethanfire** [comment]
Correct, but Mac browsers are not showing the warning and I must have just not seen in while testing on Windows Chrome.
It helps to know in full detail how you got something to not function, throw an error/warning, etc. so I can replicate the problem without winging it.

**Comment by morethanfire** [comment]
A fix for this is in release 1.3.2 https://github.com/saddlebackdev/react-cm-ui/releases/tag/1.3.2
